# Changes here will be overwritten by Copier
_commit: v1.2.0
_src_path: https://github.com/worldworm/copier-base-copier.git
answersfile_suffix: base-meta
child_template_name: copier-base
child_template_url: https://github.com/worldworm/copier-base
copier_version: '9'
copyright_license: MIT
copyright_year_start: 2023
copyright_year_today: 2024
is_bp: false
is_ext: false
is_meta: true
need_trust: false
project_description: Copier meta template for all projects.
project_emoji: 📋
project_name: copier-base-meta
ref_tech_url: ''
repository_name: copier-base-meta
repository_provider: GitHub
repository_url: https://github.com/worldworm/copier-base-meta
repository_username: worldworm
warning_early_dev: false
